"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { fetchWithSession } from "@/components/auth/client-fetch";

type Place = { id:string; name:string; address:string|null; latitude:number|null; longitude:number|null; rating:number|null; reviewCount:number|null; categories:string[]; sourceId:string|null };
type Destination = { id:string; latitude:number|null; longitude:number|null; places:Place[] };
type Trip = { id:string; city:string; country:string; travelDays:number; travelerCount:number; transportMode:string; startDate:Date; endDate:Date; totalBudgetMinor:number; currency:string; interests:string[]; destinations:Destination[]; itineraries:{id:string}[] };

export default function TripWorkspace({ trip }: { trip:Trip }) {
  const router = useRouter(); const destination = trip.destinations[0];
  const [query,setQuery] = useState(`${trip.city} tourist attractions`); const [places,setPlaces] = useState<Place[]>(destination?.places ?? []); const [selected,setSelected] = useState<string[]>([]); const [busy,setBusy] = useState(false); const [message,setMessage] = useState("");
  const selectedPlaces = useMemo(() => places.filter((place) => selected.includes(place.id)), [places,selected]);
  async function discover() { setBusy(true); setMessage(""); const response=await fetchWithSession("/api/providers/places",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query,destinationId:destination?.id,location:destination?.latitude !== null && destination?.latitude !== undefined && destination?.longitude !== null && destination?.longitude !== undefined ? {latitude:destination.latitude,longitude:destination.longitude}:undefined})}); const result=await response.json().catch(()=>({})); setBusy(false); if(!response.ok){if(response.status!==401)setMessage(result.error??"Could not discover places");return;} setPlaces(result.places); setSelected(result.places.slice(0,6).map((place:Place)=>place.id)); setMessage(`${result.places.length} places ready. Select the ones you want in your plan.`); }
  async function generate() { const candidates=selectedPlaces.filter((place)=>place.latitude!==null&&place.longitude!==null).slice(0,12).map((place)=>({id:place.sourceId??place.id,name:place.name,location:{latitude:place.latitude as number,longitude:place.longitude as number},rating:place.rating??undefined,interestTags:place.categories,estimatedVisitMinutes:90,estimatedCostMinor:0})); if(!candidates.length){setMessage("Select at least one place with a valid location.");return;} setBusy(true); const response=await fetchWithSession("/api/itineraries/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tripId:trip.id,candidates})}); const result=await response.json().catch(()=>({})); setBusy(false); if(!response.ok){if(response.status!==401)setMessage(result.error??"Could not generate itinerary");return;} router.push(`/trips/${trip.id}/itinerary`); }
  return <main className="shell"><nav className="topbar"><Link href="/">â† All trips</Link><Link href={`/trips/${trip.id}/edit`}>Edit trip</Link></nav><header className="trip-header"><div><p className="eyebrow">YOUR TRIP</p><h1>{trip.city}, {trip.country}</h1><p className="lede">{trip.travelDays} days Â· {trip.travelerCount} traveler(s) Â· {trip.transportMode.toLowerCase()}</p></div>{trip.itineraries[0]&&<Link className="button secondary" href={`/trips/${trip.id}/itinerary`}>Open itinerary</Link>}</header><section className="stats-grid"><div className="stat-card"><span>Dates</span><strong>{trip.startDate.toISOString().slice(0,10)} â†’ {trip.endDate.toISOString().slice(0,10)}</strong></div><div className="stat-card"><span>Budget</span><strong>{trip.totalBudgetMinor.toLocaleString()} {trip.currency}</strong></div><div className="stat-card"><span>Interests</span><strong>{trip.interests.join(", ")||"Open to ideas"}</strong></div></section><section className="workspace-section"><div className="section-heading"><div><p className="eyebrow">STEP 1</p><h2>Find places to visit</h2></div><span className="muted">Powered by Google Places</span></div><div className="search-row"><input value={query} onChange={(event)=>setQuery(event.target.value)} aria-label="Place search"/><button className="button primary" disabled={busy||!destination} onClick={()=>void discover()}>{busy?"Searchingâ€¦":"Discover places"}</button></div>{places.length>0?<div className="place-grid">{places.map((place)=><label className={`place-card ${selected.includes(place.id)?"selected":""}`} key={place.id}><input type="checkbox" checked={selected.includes(place.id)} onChange={()=>setSelected((current)=>current.includes(place.id)?current.filter((id)=>id!==place.id):[...current,place.id])}/><div><h3>{place.name}</h3><p className="muted">{place.rating?`â˜… ${place.rating}`:"No rating"}{place.reviewCount?` Â· ${place.reviewCount} reviews`:""}</p><p>{place.address??"Address unavailable"}</p></div></label>)}</div>:<div className="empty-card compact"><p>No places loaded yet. Search to build your candidate list.</p></div>}</section><section className="workspace-section callout"><div><p className="eyebrow">STEP 2</p><h2>Build your itinerary</h2><p className="muted">Weâ€™ll schedule the selected places around travel time, opening hours, budget, and transport mode.</p></div><button className="button primary" disabled={busy||selected.length===0} onClick={()=>void generate()}>{busy?"Planningâ€¦":"Generate itinerary"}</button></section>{message&&<p className="notice" role="status">{message}</p>}</main>;
}

